# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # config.vm.box = "Microsoft/EdgeOnWindows10"
  config.vm.box = "gusztavvargadr/windows-10-enterprise"
  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 3389, host: 33389

  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
     # Customize the amount of memory on the VM:
     vb.memory = "4096"
   end
end
