# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

	# LDAP Server
	config.vm.define "master" do |master|
      master.vm.box = "ubuntu/xenial64"
	  master.vm.provider "virtualbox" do |vb|
	    vb.memory = "256"  
	  end
      master.vm.hostname = "master"
      master.vm.network "private_network", ip: "192.168.55.102"
      master.vm.network "forwarded_port", guest:80, host:8081, auto_correct: false
  	  master.vm.synced_folder ".", "/vagrant"  	
	  master.vm.provision "shell", inline: <<-SHELL
		sudo apt-get update
		sudo apt-get -y install debconf-utils apache2 nmap
		sudo a2enmod cgi	
		sudo a2enmod ldap	
		sudo a2enmod authnz_ldap
		sudo cp /vagrant/rest /vagrant/network /usr/lib/cgi-bin/ && sudo chown www-data /usr/lib/cgi-bin/* && sudo chmod 755 /usr/lib/cgi-bin/*
		sudo mkdir -p  /var/www/html/data && sudo chown www-data:www-data /var/www/html/data 
		# OpenLDAP mit Admin UI - http://localhost:8081/phpldapadmin
		export DEBIAN_FRONTEND=noninteractive
		sudo debconf-set-selections <<<'slapd slapd/internal/generated_adminpw password admin'
		sudo debconf-set-selections <<<'slapd slapd/password2 password admin'
		sudo debconf-set-selections <<<'slapd slapd/internal/adminpw password admin'
		sudo debconf-set-selections <<<'slapd slapd/password1 password admin'
		sudo apt-get install -y slapd ldap-utils phpldapadmin
		# Patch Standarddomain
		sudo sed -i -e's/dc=example,dc=com/dc=nodomain/' /etc/phpldapadmin/config.php
		sudo service apache2 restart 
SHELL
    end
 end
